package util.api.exception

class ReceiveFailedException : RuntimeException("Receive was failed!!") {
}